apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-backend
  template:
    metadata:
      labels:
        app: laravel-backend
    spec:
      containers:
        - name: laravel
          image: laravel-backend:latest     # Built inside Minikube
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: app_db
            - name: DB_USERNAME
              value: app_user
            - name: DB_PASSWORD
              value: app_pass
