apiVersion: v1
kind: Service
metadata:
  name: laravel-backend
spec:
  selector:
    app: laravel-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
