apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react
          image: react-frontend:latest        # Local image
          imagePullPolicy: Never              # Use local Docker image built in Minikube
          ports:
            - containerPort: 80               # NGINX exposes port 80
