apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80            # exposed for ingress
      targetPort: 80      # since NGINX serves on 80 now
